name: CI

on: [push]

jobs:
  auto-tests:
    name: Pytest (${{ matrix.platform }} - ${{ matrix.compiler }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-24.04
            compiler: gcc

          - platform: ubuntu-24.04
            compiler: clang

          - platform: macos-latest
            compiler: clang

          - platform: windows-2022
            compiler: cl

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Ensure clang is available (only if required)
        if: runner.os == 'Linux' && matrix.compiler == 'clang'
        run: |
          sudo apt-get update -y && sudo apt-get install -y clang
          sudo ln -sf $(command -v clang)    /usr/local/bin/cc
          sudo ln -sf $(command -v clang++)  /usr/local/bin/c++

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Create 3.10 virtualenv
        run: uv venv .venv --python=3.10

      - name: Install project (uv sync)
        run: uv sync

      - name: Run tests
        run: uv run pytest -s --log-cli-level=debug

      - name: Create 3.13 virtualenv
        run: uv venv .venv --python=3.13

      - name: Install project (uv sync)
        run: uv sync

      - name: Run tests
        run: uv run pytest -s --log-cli-level=debug
