name: CI

on: [push]

jobs:
  auto-tests:
    name: Pytest (${{ matrix.platform }} – ${{ matrix.compiler }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux – GCC
          - platform: ubuntu-24.04
            compiler: gcc

          # Linux – Clang
          - platform: ubuntu-24.04
            compiler: clang

          # macOS – system Clang
          - platform: macos-latest
            compiler: clang

          - platform: windows-2022
            compiler: cl

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Linux images already have GCC; we only need Clang for that variant
      - name: Ensure clang is available
        if: runner.os == 'Linux' && matrix.compiler == 'clang'
        run: |
          sudo apt-get update -y && sudo apt-get install -y clang
          sudo ln -sf $(command -v clang)    /usr/local/bin/cc
          sudo ln -sf $(command -v clang++)  /usr/local/bin/c++

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ matrix.platform }}-${{ matrix.compiler }}-${{ hashFiles('uv.lock') }}

      - name: Create virtualenv
        run: uv venv .venv --python=3.10

      - name: Install project (uv sync)
        run: uv sync

      - name: Run tests
        run: uv run pytest -s --log-cli-level=debug
